# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
last_name: muhaemin
email: muhaemin1998@gmail.com
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  A simple, whitespace theme for academics. Based on design.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>
keywords: developer, jekyll-theme, academic-website # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: "https://mhaemnn.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

twitter_username: jekyllrb
github_username: mhaemnn

# Build settings
theme: minima
plugins:
  - jekyll-feed
