# -------------------------------------------------------------------------
# Settings
# -------------------------------------------------------------------------

title: muhaemin
email: muhaemin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
url: "https://mhaemnn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username: jekyll


# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------


